Sage-Bionetworks-Workflows/nextflow-infra

.github/CODEOWNERS
.github/workflows/aws-deploy.yaml
Pipfile
Pipfile.lock

I'm not sure what's the best way of testing these CI workflows other than reviewing them and making sure they behave as expected once merged. 
I've opted for a setup where we have two stack groups: `dev` and `prod`. The `dev` stacks will be deployed to the `workflows-nextflow-dev` account whereas the `prod` stacks will be deployed to the `workflows-nextflow-dev` and `workflows-nextflow-prod` accounts. Another pattern I noticed [here](https://github.com/Sage-Bionetworks/iAtlas-infra/tree/staging/config) is to have `dev`, `prod`, and `common`. 
You can ignore the change affecting the `CODEOWNERS` file. I just removed the extra line at the end of the file to satisfy the pre-commit test.

Add draft CI workflow

---

.gitignore
config/config.yaml
config/prod/s3-cfn-templates.yaml

For now, the only use case is for storing the templates from the [aws-genomics-workflows-library](https://github.com/Sage-Bionetworks-Workflows/aws-genomics-workflows-library) repository. 
@zaro0508: Is there a reason why you deploy templates to an S3 bucket instead of downloading from GitHub directly in the sceptre pre-hooks? If you think the S3 deployment is essential, then your review of this PR would be appreciated.

Create S3 bucket for storing CloudFormation templates

---

config/prod/nextflow-forge-iam-policy.yaml
config/prod/nextflow-forge-service-user.yaml
templates/nextflow-forge-iam-policy.yaml
templates/nextflow-forge-service-user.yaml

This PR adds a policy and service account user for NextFlow to provision batch resources in our AWS account through their [Forge option](https://help.tower.nf/docs/compute-envs/aws-batch/#forge).

Add NextFlow service account policy and user

---

.github/workflows/aws-deploy.yaml
config/common/nextflow-forge-service-user.yaml

1. Fix reference to dependencies that were moved from prod to common
2. Use appropriate service role for each AWS account. Additional secrets have already been added to the organization.

Fix CICD refactor issues

---

config/common/nextflow-aurora-mysql.yaml
config/develop/nextflow-aurora-mysql.yaml
config/prod/nextflow-aurora-mysql.yaml
templates/nextflow-aurora-mysql.yaml

For [WORKFLOWS-10](https://sagebionetworks.jira.com/browse/WORKFLOWS-10), this creates a serverless Aurora cluster in the nextflow VPC using two private subnets. The Data API is enabled, which allows us to use awscli to query the database, after authenticating to a role with permissions. For example,
```
aws  rds-data execute-statement \
--resource-arn $AURORA_CLUSTER_ARN \
--schema mysql \
--secret-arn $AURORA_SECRET_ARN \
--sql 'SHOW DATABASES;'
```
I have tested spinning this stack up with and without a snapshot in the nextflow-dev account.
Related planned work:
- Bootstrapping, if we intend to do that through CFN, will be set up in [WORKFLOWS-12](https://sagebionetworks.jira.com/browse/WORKFLOWS-12).
- A logging system will be set up in …

Add an AWS Aurora cluster required for NextFlow Tower app

---

templates/nextflow-aurora-mysql.yaml

This adds a Lambda to perform some bootstrapping statements on the tower database in the Aurora DB cluster.
https://sagebionetworks.jira.com/browse/WORKFLOWS-12

Add lambda to bootstrap tower database

---

.github/workflows/aws-deploy.yaml
CONTRIBUTING.md
config/develop/bgrande-test-service-user.yaml
config/develop/nextflow-vpc.yaml
config/develop/peer-nextflowdev-vpc-admincentral.yaml
config/develop/s3-cfn-templates.yaml
config/prod/nextflow-vpc.yaml
config/prod/peer-nextflowprod-vpc-admincentral.yaml

Prompted by Sage-Bionetworks/scicomp-provisioner#487.

Use `-O` option for storing `wget` output to avoid caching

---

.github/workflows/aws-deploy.yaml
Pipfile
Pipfile.lock

The current github actions workflow uses a sceptre action which does not support custom resolvers. This is limits how we have come to use sceptre -- for example, we won't be able to use the ever-popular `sceptre-ssm-resolver`. I have use cases for using `sceptre-cmd-resolver`, so I have refactored the workflow to use the pipenv environment instead and forgo the sceptre action.
I also want to make more of a case for using pipenv in this way. It makes sense that you set up your dependencies file -- whether that is `requirements.txt` or `Pipfile` -- that can be used in any environment. In other words, it creates an environment that I can use to build whether I am developing or the build action is running on github. When we use the sceptre custom action, we're effectively departing from the …

WORKFLOWS-25: support sceptre resolvers in build

---

.pre-commit-config.yaml
Pipfile.lock
config/develop/nextflow-ecs-capacity.yaml
config/develop/nextflow-ecs-cluster.yaml
config/develop/nextflow-vpc.yaml
templates/nextflow-ecs-capacity.yaml
templates/nextflow-ecs-cluster.yaml

[WORKFLOWS-21](https://sagebionetworks.jira.com/browse/WORKFLOWS-21)
This creates an ECS cluster that has a single instance in it.
One disadvantage of doing this is that we can't export the PublicIp attribute as we would if this were configured as `AWS::EC2::Instance`, and that is required for the [ECS task stack](https://sagebionetworks.jira.com/browse/WORKFLOWS-22). However, I will probably be able to use `!rcmd` to get the PublicIP for that parameter.
PR depends on #19 and on https://github.com/Sage-Bionetworks/aws-infra/pull/315

WORKFLOWS-21: Add ECS cluster stack

---

templates/nextflow-forge-iam-policy.yaml

Update nextflow-forge-iam-policy to reflect [Seqera's updated forge policy](https://github.com/seqeralabs/nf-tower-aws/blob/master/forge/forge-policy.json), which allows for EFS permissions

Update Nextflow IAM Forge Policy

---

.github/CODEOWNERS
config/common/smtp-credentials.yaml
templates/smtp-credentials.yaml

[WORKFLOWS-11](https://sagebionetworks.jira.com/browse/WORKFLOWS-11): NextFlow needs SMTP credentials set up so that Tower can send email.
This is adapated from [tsamuel33/aws-smtp-credentials](https://github.com/tsamuel33/aws-smtp-credentials).

Add stack that produces SMTP credentials

---

config/develop/peer-nextflowdev-vpc-admincentral.yaml
config/prod/peer-nextflowprod-vpc-admincentral.yaml

VPC peering is no longer needed.

Remove VPC peering

---

config/develop/nextflow-aurora-mysql.yaml
templates/nextflow-aurora-mysql.yaml

Fix problem with kms key use in Aurora. The build is currently broken b/c the lambda role is attempting to use the workflows-infra key, but it is not a principal of that key.

KMS key for bootstrapping must be in same stack with Lambda

---

config/develop/tower-dev-certificate.yaml
config/prod/tower-certificate.yaml

Acc. to various slack conversations as documented in [WORKFLOWS-40](https://sagebionetworks.jira.com/browse/WORKFLOWS-40), we have to create separate certificates for our new subdomains.

Add ACM certificates for subdomains

---

templates/nextflow-ecs-cluster.yaml

Adds a CapacityProvider to implement managed scaling. This allows the cluster to add an instance which will accommodate a new, updated task before spinning down the old one. It takes 5-6 minutes for this turnover to happen and then another ~15 minutes to shut down the second cluster instance. Possibly we could shorten the latter by adjusting TargetCapacity -- but this seems to be working nicely now.

[WORKFLOWS-44] Add Managed Scaling

---

config/develop/nextflow-efs-file-system.yaml
config/develop/nextflow-tower-config-bucket.yaml
templates/nextflow-efs-file-system.yaml

This is a follow-up to #51. The EFS file system has been encrypted as requested.

[WORKFLOWS-38] Encrypt EFS file system

---

templates/nextflow-ecs-task-definition.yaml

I'm not sure if 30 days is appropriate as the retention period for these logs. We could make it shorter. 
You can find the test-deployment of the log group in the `nextflow-dev`: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Ftask$252Fnf-tower

[WORKFLOWS-42] Send tower container logs to Cloudwatch

---

config/common/budget-compute.yaml
config/common/budget-other.yaml
config/common/budget-storage.yaml
config/config.yaml
templates/budget.yaml

I've adapted the [budget template](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/Billing/budgets.yaml) from aws-infra and added cost filters. This way, we can create more granular budget alerts. 
I propose three budgets: compute costs, storage (S3) costs, and everything else. The compute costs will spike, so the threshold on that is higher and will probably need to be adjusted once we have a better sense of compute needs. The storage costs will gradually increase as more projects are onboarded and more workflows are run. The "other" category should capture basic operating costs, which are generally stable. This would have caught the NAT gateway traffic that happened in September. I've set a purposely low threshold on this. 
The thresholds were estimated based on …

[WORKFLOWS-67] Create more granular budget alerts

---

CONTRIBUTING.md
README.md
bin/mirror-igenomes.sh
config/develop/igenomes-bucket.yaml
config/prod/igenomes-bucket.yaml
templates/public-bucket.yaml

I was hoping to re-use the `s3-bucket-v2.j2` template from aws-infra, but I didn't want to have to deal with the [S3objects macro](https://github.com/Sage-Bionetworks/aws-infra/tree/master/lambdas/cfn-s3objects-macro), especially because it's not relevant to our use case. I opted for adapting the template for our purposes. 
I'm still figuring out how to copy the files. Unfortunately, interacting with the nf-core bucket requires using `--no-sign-request`, which then prevents the requests to our bucket to work since they're unauthenticated (see example command below). I'm currently staging files locally on a Service Catalog instance. I included a script that I will run once the bucket is deployed to production. 
```console
aws s3 --no-sign-request sync "s3://source-bucket/" …
```

[WORKFLOWS-70] Create public buckets for iGenomes reference files

---

Pipfile
Pipfile.lock
config/develop/nextflow-r53-hostedzone.yaml
config/develop/nextflow-s3-vpc-endpoint.yaml
config/develop/nextflow-vpc.yaml
config/develop/s3-cfn-templates.yaml
config/develop/tower-dev-certificate.yaml
config/prod/nextflow-r53-hostedzone.yaml
config/prod/nextflow-s3-vpc-endpoint.yaml
config/prod/nextflow-vpc.yaml
config/prod/tower-certificate.yaml

As I was preparing this PR, I noticed that the new template handlers haven't made it into a new Sceptre release. It's currently only on the `master` branch. I think we should wait until a new release is minted. 
@zaro0508: Do you know when we should expect a new Sceptre release?

[WORKFLOWS-68] Use Sceptre template handlers for remote templates

---

.github/workflows/aws-deploy.yaml
README.md

In this PR, I propose using a Confluence wiki page to disseminate important information. I was initially going to create a Google Group, but I like how diffs are emailed to watchers on Confluence. Edits can optionally be published without notifying users in case we need to add less critical information. 
An added benefit of this approach is that we don't have to trigger our CI workflow with frequent edits to the README. 
Here's the Confluence page: https://sagebionetworks.jira.com/l/c/1hm4NP7a. Only Tess, Tom, and I have edit-access at the moment. Let me know if there's any important information that should be added.

Migrate important info to Confluence wiki page with watchers

---

bin/mirror-igenomes.sh

I realized that setting the bucket ACL to `public-read` only allows unauthenticated users to list the bucket contents. It doesn't grant access to the objects themselves. I looked into granting public access to objects using a bucket policy, but this cannot be done without editing the Lambda function, which assigns and maintains the bucket policy. 
Instead, since the contents of the iGenomes bucket aren't expected to change very often, I opted to update all objects with the `public-read` ACL. This PR makes note of this requirement when mirroring iGenomes files, but I'm currently running the following command to retroactively deploy this change. From what I can tell, this does the trick. 
```
aws s3 cp s3://sage-igenomes/igenomes/ s3://sage-igenomes/igenomes/ --recursive --acl public-read …
```

Ensure that iGenomes reference files are public

---

bin/configure-tower-projects.py
config/develop/nextflow-ecs-task-definition.yaml
config/prod/nextflow-ecs-task-definition.yaml

I was originally waiting for a major release before upgrading Tower, but Paolo suggested this patch release might address the issue I reported [here](https://git.seqera.io/sage/nf-support/issues/7#issuecomment-6016). I already deployed this change to Nextflow-dev, and ECS transitioned to the new task definition as expected. I'm now running a test in Tower-dev to see whether the issue has been fixed or not. 
**Edit:** This PR now updates Tower to `v21.06.4`, which was released to address the following error message that I reported to Seqera. This requires compute environments to be re-created so their configuration can be updated. Hence, I've also updated the Tower configuration script to create versioned compute environments (instead of managing a default CE, which would be more …

[WORKFLOWS-55 | WORKFLOWS-96] Upgrade Nextflow Tower to `v21.06.4`

---

CONTRIBUTING.md
config/common/cfn-s3objects-macro.yaml
config/develop/nextflow-tower-config-bucket.yaml
config/prod/nextflow-tower-config-bucket.yaml
templates/nextflow-tower-config-bucket.yaml
tower-config/tower.yaml

Unfortunately, Nextflow Tower seems to issue plenty of requests to GitHub, which results in rate limits being imposed. These rate limits manifest in the form of uninformative errors like `Unknown pipeline repository or missing credentials`. In this PR, we are configuring Tower to authenticate requests to GitHub using a service account, which should have higher rate limits than unauthenticated requests. 
At the same time, I'm taking the opportunity to switch to using the `S3Objects` macro to obviate the need for a post-launch Sceptre hook. Shout-out to @tthyer for fixing the `S3Objects` macro!

[WORKFLOWS-84] Provide default GitHub credentials

---

templates/tower-project.yaml

I propose that we switch to the new `BucketOwnerEnforced` setting for S3 object ownership. For more information, check out [these docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html). The gist is that objects uploaded by other AWS accounts (_e.g._ sandbox IAM roles) are automatically owned by the bucket owner, which ensures that the bucket policies are enforced on all objects. 
The big gain here is that users don't have to arbitrarily include the `--acl bucket-owner-full-control` option when uploading using the AWS CLI. Unfortunately, omitting this option results in a cryptic `Access Denied` error. Avoiding this error by getting rid of the requirement for the `bucket-owner-full-control` canned ACL will make Tower projects more user-friendly.

[WORKFLOWS-99] Switch to `BucketOwnerEnforced` object ownership setting

---

CONTRIBUTING.md
README.md
bin/configure-tower-projects.py

We found that Tower users weren't getting access to the right workspaces. As a first-pass attempt to resolving this issue, I'm updating the Tower configuration script to create teams per project per role and adding these teams to the relevant workspaces. I'm also performing the additional step of removing unexpected users from each team to make sure they remain in sync with the Sceptre config file. 
I was able to test the updated script in Tower-dev. Once it's deployed to Tower-prod, I'm going to remove all of the users that are listed individually on workspaces. Because these users will have been added via a team, no one should suffer a lapse of access (unless they weren't supposed to have access to the workspace in the first place). 
**Edit:** As I show in [this …

[WORKFLOWS-181] Create and add teams to Tower workspaces

---

.github/workflows/aws-deploy.yaml
README.md
bin/configure-tower-projects.py

I ran into the following error after merging #96 when creating the `challenge-infra-test-project-maintainers` team in Tower-prod. I've added a note to the README, and I'm trimming the `-project` suffix from the team name to compensate for the addition of the `-maintainers` or `-viewers` suffix. 
```
{'message': 'Team name must contain a minimum of 1 and a maximum of 38 alphanumeric characters separated by dashes or underscores'}
```
I'm disabling debug mode now that I figured out the issue with the #96 deployment.

[WORKFLOWS-181] Ensure shorter team names due to length limit

---

bin/configure-tower-projects.py

After merging #96 and #97, I realized that people were still missing from certain workspaces. I finally identified the root cause of WORKFLOWS-181. Because there are more than 10 members in our Sage Tower organization, responses started to span multiple pages, but my Tower client was only considering the first page of results (10). 
Sadly, this wasn't caught because I had a [poorly written for-loop](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/f6f0de41f010195ed9a46979936ff4ab89a4b2cf/bin/configure-tower-projects.py#L683-L685) that was defaulting to the last member in the list. It's a silly mistake on my part. I've addressed both instances of this pattern with a more defensive approach. 
In reviewing the [Tower API docs](https://tower.nf/openapi/index.html) for how to …

[WORKFLOWS-181] Add support for paged requests

---

bin/empty-queue.sh

I've ended up with AWS Batch job queues with thousands of jobs after cancelling a workflow run. Unfortunately, there's no way to empty a queue with one request. You need to terminate each job individually. This script uses GNU parallel to speed up the process. The script is based on this [AWS support article](https://aws.amazon.com/premiumsupport/knowledge-center/batch-jobs-termination/).

Add script for emptying an AWS Batch queue

---

config/projects-prod/example-project.yaml
config/projects-prod/ntap-add5-project.yaml
config/projects-prod/ntap-gdp5-project.yaml

Naming is hard. Is `ntap-gdp5-project` intuitive? It's derived from the official project name, NTAP Genomic Data Processing, Addendum #5. Another option would be  `ntap-add5-project`.

Create `ntap-gdp5-project` stack

---

config/infra-dev/nextflow-ecs-service.yaml
templates/nextflow-ecs-cluster.yaml
templates/nextflow-ecs-service.yaml

I was working on #107 and I decided to take a stab at the auto-scaling issue we've been having with the Tower ECS service. Essentially, it would get stuck at two instances, even if the task was only running on a single instance. I implemented everything that was recommended by AWS Support in their latest response, and I think auto-scaling works as expected now. After launching the service, there were two instances, but after some time, that automatically dropped to a single instance. 
This will basically halve our EC2 costs for hosting Tower, which amounts to saving $10/day (or $300/mo). 
Depends on #107

[WORKFLOWS-53] Fix auto-scaling for Tower ECS service

---

config/common/maintenance.yaml

Version `v0.4.0` of aws-infra extended the duration of the maintenance stack cron jobs. @ahayden and @zaro0508 mentioned that I should be using this updated version.

Update maintenance stack with longer cron duration

---

config/infra-dev/nextflow-ecs-task-definition.yaml
config/infra-prod/nextflow-ecs-task-definition.yaml
src/tower/resources/environment.yaml
templates/nextflow-ecs-task-definition.j2

Disabling the user workspaces, which cannot be used anyways since they don't have credentials, will reduce user confusion.

Disable private Tower workspaces per user

---

config/infra-dev/s3-cfn-templates.yaml
templates/nextflow-tower-config-bucket.yaml
templates/tower-project.yaml

CloudFormation defaults to **not** blocking public access on S3 buckets. This PR addresses that for public that ought not to be public.

[WORKFLOWS-258] Block all public access on S3 buckets

---

bin/configure-tower-projects.py
config/config.yaml

This PR aims to mitigate the issue with EBS auto-scaling that results in orphaned EBS volumes. Two strategies are employed:
- **Enable Fusion mounts for relevant S3 buckets:** The main advantage with this strategy is that parallel jobs on an AWS Batch EC2 instance will not download the same files in parallel (if applicable). Instead, they will read the files from a common source, which should slow down how much the EBS volumes grow. 
- **Increase initial EBS volume size:** This strategy should buy some time before the volume needs to be auto-scaled. This would hopefully result in fewer auto-scaling events happening within seconds of each other, which in turn risks triggering EC2 API rate limits. 
Since we're upgrading the CE version, I'm also upgrading the Tower version and another bit of …

[WORKFLOWS-293] Mitigate issue with orphaned EBS volumes (and upgrade Tower)

---

bin/configure-tower-projects.py

Unfortunately, Fusion hasn't stopped orphaned EBS volumes from appearing in the account. It's also been causing at least two unprecedented issues, which has led me to decide to disable it.

[WORKFLOWS-410] Disable Tower Fusion in light of persistent issues

---

config/projects-prod/genie-bpc-project.yaml

Chelsea will have to do step 2 to get jumpcloud access to these accounts, but this will at least allow her to access the tower project.

Add chelsea nayan to GENIE read only

---

bin/setup-ssh-via-ssm.sh

I often find myself having to remotely access EC2 instances using SSM. I typically want to use SSH because I either want to copy files off of the EC2 instance using SCP or edit files using VS Code (with the SSH Remote extension). This requires me running through the same steps every time. In light of this, I decided to capture those commands in a shell script that can automate the setup and minimize mistakes.
Here's an example command and associated output:
```console
❯ bash setup-ssh-via-ssm.sh i-0421aea79957b510c
Running the following shell script on i-0421aea79957b510c...
cd
mkdir -p .ssh;
echo [...] > .ssh/authorized_keys;
sudo cp -r .ssh /home/ec2-user/;
sudo chmod 700 /home/ec2-user/.ssh;
sudo chmod 600 /home/ec2-user/.ssh/authorized_keys;
sudo chown -R ec2-user:ec2-user …
```

Shell script for configuring SSH via SSM

---

templates/tower-project.yaml

At the time of writing, access between Tower projects is impossible due to KMS encryption. This PR builds on that by restricting access using identify and resource policies. There were two "paths" that I wanted to block:
1. One of the IAM roles that are automatically created by Tower Forge is attached to the `AmazonS3ReadOnlyAccess` managed policy, which would grant it access to all S3 buckets within the account. In theory, these roles aren't used to access project buckets, but it's better to be safe than sorry. To address this, I added a specific block against all roles created by Forge (_i.e._ prefixed with `TowerForge-`). 
2. The head and worker job roles created by the `tower-project` template were also attached to the overly permissive `AmazonS3ReadOnlyAccess` policy. I dropped this …

[WORKFLOWS-455] Harden separation in S3 access between Tower projects

---

.github/workflows/aws-deploy.yaml
.pre-commit-config.yaml
config/projects-ampad/config.yaml
config/projects-ampad/example-ampad-project.yaml
config/projects-ampad/jared-hendrickson-project.yaml
config/projects-ampad/strides-ampad-project.yaml
config/projects-ampad/wei-an-chen-project.yaml
config/projects-dev/config.yaml
config/projects-dev/example-dev-project.yaml
config/projects-prod/amp-ad-project.yaml
config/projects-prod/config.yaml
config/projects-prod/ctf-swnts-project.yaml
config/projects-prod/example-project.yaml
config/projects-prod/genie-bpc-project.yaml
config/projects-prod/htan-project.yaml
config/projects-prod/imcore-project.yaml
config/projects-prod/jhu-biobank-nf-project.yaml
config/projects-prod/mc2-mcmicro-project.yaml
config/projects-prod/nf-ntap5-biobank-jineta.yaml
config/projects-prod/nfri-ctf-nf1-project.yaml
config/projects-prod/ntap-add5-project.yaml
config/projects-prod/ntap-cnf-cell-project.yaml
config/projects-prod/robert-allaway-project.yaml
config/projects-prod/sophia-jobe-project.yaml
config/projects-prod/ucf-dod-nf2-project.yaml
config/projects-prod/verena-chung-project.yaml

A lot of files of being changed in this PR, but most of it was done with search and replace queries in VS Code (example below). It basically moves the common prefix for the TowerViewer assumed-role ARN to the Sceptre config. 
**Edit:** I'm not sure what's wrong with the pre-commit in the CI workflow, so I'll need to debug that too. 
```
Search:   arn:aws:sts::035458030717:assumed-role/AWSReservedSSO_TowerViewer_5919a1dd6875ede2/([\w@.]+)
Replace:  '{{stack_group_config.tower_viewer_arn_prefix}}/$1'
```

[WORKFLOWS-481] Parametrize TowerViewer assumed-role ARN prefix

---

bin/configure-tower-projects.py

This PR addresses an issue that got introduced when we reverted from managing access using teams back to using users (c77aac2da7ac253a187b6461b022d4307fc18e9e). While the teams functionality removed any unexpected team members, this feature had not been implemented yet for the users functionality. This PR addresses this gap. 
In practice, this should ensure that any users that are removed from Tower project stacks will also be removed from the corresponding Tower workspace. 
Depends on #143

[IBCDPE-404] Remove unlisted participants in each workspace

---

config/projects-dev/orca-dev-project.yaml

In response to a discussion in https://github.com/Sage-Bionetworks-Workflows/orca-recipes/pull/3, we might want to explore using the Tower-dev instance for testing purposes with Airflow.

[ORCA-105] Create `orca-dev-project` Tower project

---

README.md

The main objective of this PR is to update the Getting Help section in the README, but I also took the opportunity to fix outdated parts. 
One question I have is whether we should move these docs to the [Getting Started with Nextflow and Tower](https://sagebionetworks.jira.com/wiki/spaces/WF/pages/2191556616/Getting+Started+with+Nextflow+and+Tower) Confluence page so everything is in one place. I would replace the instructions with a link to the relevant section on the wiki. If so, I can update this PR to achieve that.

[WORKFLOWS-479] Update README for new support process

---

bin/configure-tower-projects.py

By specifying more than one ARN that has a specific user's email, you run into the possibility of having duplicated emails.  This removes duplicates.
Full disclosure - I haven't tested this locally.   It could be interesting to have a full set of instructions to test these scripts within the dev environment.  
For instance
1. Create dev stack in `config/projects-dev`
2. pipenv run ...
3. success?

[WORKFLOWS-497] Only return non-duplicated emails

---

config/projects-prod/mc2-mcmicro-project.yaml

I'm using existing functionality in the `configure-tower` script to ensure that the external users for the MC2 project are added to the Tower workspace. This is the quickest way of achieving that (other than manually adding them again). The better approach would be to add a new section in the YAML file (_e.g._ using `scepter_user_data`), but since we expect these stacks to be revamped soon to support custom AWS Batch compute environments, I opted against that for expediency.
This is a low-risk PR and one of our users is blocked, so I'm going to merge immediately, but I'm still open to feedback.

Ensure that MC2 external users are added to Tower

---

bin/configure-tower-projects.py

@adamjtaylor needs GPUs to be enabled for the `mc2-mcmicro-project` workspace. I'm wondering if we can enable GPUs across all compute environments to avoid having to support a distinction between GPU-enabled and GPU-disabled workspaces. This is feasible because we expect AWS Batch to select the cheapest instance types where possible, so if a job doesn't ask for GPUs, then there should be no risk for a more expensive instance type (_e.g._ one that is GPU-enabled) to be selected. I've [asked](https://nextflow.slack.com/archives/C02T97HAV5M/p1676661020433299) if enabling GPUs in the Tower compute environment has any drawbacks. 
I'm also taking this opportunity to start using `SPOT_CAPACITY_OPTIMIZED` for our spot compute environments. This is a smarter allocation strategy where instance …

[IT-2364] Improve allocation strategy and instance types

---

bin/configure-tower-projects.py

As part of #161, I increased the number of available instance types for the Tower compute environments. Unfortunately, AWS Batch's allocation strategy tends to result in bigger instance types being used (_e.g._ `r6in.24xlarge` with 96 vCPUs and 768 GB of memory, costing over $8/hr). While this instance might make sense when a bunch of jobs are submitted, it's problematic when a single job is left running on it, resulting in poor instance utilization. 
In this PR, I'm limiting the instance types to `8xlarge` (32 vCPUs) to ensure more incremental scaling. The most expensive instance type in the updated list costs $2/hr, so it's significantly less "painful" to have a single job running on it. While I was refining the list, I dropped instance type subtypes that are more expensive (_e.g._ …

[WORKFLOWS-515] Limit to cheaper `8xlarge` instance types

---

bin/configure-tower-projects.py

Currently, the AWS Batch allocation strategy (`BEST_FIT_PROGRESSIVE`) has a tendency to provision larger instances because they're cheaper per vCPU. However, this is problematic because you end up with a head job (16 vCPUs) sharing resources with worker jobs on a larger instance (32 vCPUs). If these jobs are well-behaved, they shouldn't use more than the allocated amount of memory or CPUs, but they do cause big spikes in network traffic when staging or uploading files. In turn, this causes the network bandwidth to become saturated, preventing the head job from being able to communicate updates to Tower. 
This PR changes the allocation strategy to `BEST_FIT`, which will prefer smaller instance types. Hence, when the head job is scheduled, an instance type that only fits it (16 vCPUs) will …

[WORKFLOWS-517] Switch to `BEST_FIT` for smaller instances

---

templates/tower-project.j2

Some projects stage large files that don't need to remain in the scratch bucket for long. This PR introduces shorter data expiration lifecycle rules as a short-term solution until Nextflow improves their file management and/or fix the `cleanup` functionality.

[IBCSPRT-159] Add shorter data expiration lifecycle rules

---

CONTRIBUTING.md
config/infra-ampad/wave-ecr-user.yaml
config/infra-ampad/workflows-kms-key.yaml
config/infra-dev/wave-ecr-user.yaml
config/infra-prod/wave-ecr-user.yaml
templates/wave-ecr-user.yaml

In preparation of using Wave, we need to authenticate all requests to container registries. I identified the 4 most commonly used registries: Docker Hub, Quay.io, GHCR, and ECR. The first three have their credentials stored in LastPass, and I manually ported them over to Secrets Manager (documented in `CONTRIBUTING.md`). The ECR credentials are account-specific, so I authored a CloudFormation stack that creates an IAM user and grants it a minimal set of ECR permissions. I haven't tested whether this works with Wave yet. 
It hurts having stacks that are so similar in the various `infra-*` subfolders, but I don't see any way around it because each account has its own administrator role that needs access to the `workflows-infra` KMS key. 
**Edit:** I intentionally did not update the Tower …

[ORCA-171] Create container registry credentials for Wave service

---

templates/nextflow-ecs-task-definition.j2

Now that we are persisting the Redis cache between deployments, we are running into corruption issues when we re-deploy Tower. This draft PR demonstrates one way of solving the issue, but I would prefer preventing it altogether. 
In this PR, we are automatically running the `redis-check-aof` command on launch (like the migrate database command) before launching Redis. I'm not sure if the behavior is defined if you have an existing Redis instance accessing this file while it's being fixed by another process. This is largely why I would prefer preventing this issue. 
**Edit:** I test this, and it seems to work. Also, Seqera didn't respond with anything particularly useful, so I'm okay with moving forward with this stop-gap solution until we work on a more permanent approach.

[WORKFLOWS-521] Check Redis append-only file first

---

templates/nextflow-ecs-cluster.yaml

EC2 Launch configurations has been deprecated[1] in favor of LaunchTemplate.
[1] https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/

[IT-2376] Switch from LaunchConfiguration to LaunchTemplate

---

templates/nextflow-aurora-mysql.yaml

Update the template used to create kms key to v0.6.83 which contains an KeyArn[1] as an output and more
expansive permission[2].  This will assist with the creation of downstream resources.
[1] Sage-Bionetworks/aws-infra@04c5b11
[2] Sage-Bionetworks/aws-infra@177f632

Update the kms key template

---

src/sceptre/variables/ampad.yaml

Due to heavy usage of the AMP-AD tower workspace, we are bumping the compute and storage costs up to 10k.

Bump AMP-AD budgets

---

.github/workflows/main.yaml

Update github action deployment strategy to use a specific branch approach
* deploy to nextflow dev only upon a merge to the `dev` branch
* deploy to nextflow prod only upon a merge to the `prod`  branch
* only deploy to ampad after a deployment to prod.
Todo after merging this PR:
* create a `dev` and `prod` branch
* delete the `main` branch
The new workflow will be:
* Create PR targeting the `dev` branch
* Review and approve PR
* Merge to the dev branch
* Deploy to nextflow dev
* [Optional] Create PR for merge from dev  branch to prod branch 
* [Optional] Review and approve PR
* Merge dev branch to prod branch
* Deploy to prod and ampad 
Note: Optional steps can be replaced with a direct push of the merge to the prod branch

[IT-2790] Change release workflow

---

.github/workflows/main.yaml
.github/workflows/rw-deploy.yaml

This is an update to use setup-python action to cache pipenv[1]
dependencies. Hopefully this will also fix the pipenv caching problem
we've been seeing recently.  This also moves `pipenv install` from the
deploy pipeline to the validation pipeline thus testing dependencies
sooner in the CI workflow.
[1] https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

[IT-2793] Fix pipenv cache in GH action
