Sage-Bionetworks-Workflows/nextflow-infra

config/prod/nextflow-forge-service-user.yaml, config/prod/nextflow-launch-iam-policy.yaml, templates/nextflow-forge-service-user.yaml, templates/nextflow-launch-iam-policy.yaml
This is the launch policy, containing permissions the NextFlow service user needs to launch workflows
=> Add launch policy for NextFlow service user

.github/workflows/aws-deploy.yaml, config/develop/peer-nextflowdev-vpc-admincentral.yaml, config/prod/peer-nextflowprod-vpc-admincentral.yaml
This PR is setting up the routes to VPN.
=> IT-1223: Add routes to VPN and update Sceptre action

config/common/workflows-kms-key.yaml, config/config.yaml, templates/workflows-kms-key.yaml
This adds a KMS key specifically for workflows infrastructure -- we can use this in the SMTP stack, for example.
=> Add KMS keys for workflows-specific infrastructure

.gitignore, templates/nextflow-aurora-mysql.yaml
See [WORKFLOWS-17](https://sagebionetworks.jira.com/browse/WORKFLOWS-17) for more context and discussion.
=> WORKFLOWS-17: Enable Aurora DB logging via CloudWatch

config/common/nextflow-tower-secret.yaml, config/develop/nextflow-aurora-mysql.yaml, templates/nextflow-aurora-mysql.yaml, templates/nextflow-tower-secret.yaml, templates/workflows-kms-key.yaml
[WORKFLOWS-36](https://sagebionetworks.jira.com/browse/WORKFLOWS-36)
- add admins to workflows-infra key
- use in aurora stack and new tower secrets stack for encryption
=> WORKFLOWS-36 use custom keys

config/develop/nextflow-vpc.yaml, config/prod/nextflow-vpc.yaml
Adds second public subnet required for ALB.
=> Update VPC template version to the v0.3.0 tag

config/prod/nextflow-aurora-mysql.yaml
This pr brings prod into parity with dev for the aurora stack
=> Update prod config for nextflow-aurora-mysql template changes

templates/nextflow-ecs-cluster.yaml
=> [WORKFLOWS-44] Enable metrics collection for autoscaling group

templates/nextflow-ecs-task-definition.yaml
=> [WORKFLOW-42] TESTING

config/common/smtp-credentials.yaml, config/common/workflows-kms-key.yaml, config/develop/nextflow-aurora-mysql.yaml, config/prod/nextflow-aurora-mysql.yaml, templates/nextflow-aurora-mysql.yaml, templates/smtp-credentials.yaml, templates/workflows-kms-key.yaml
Now that #50 is merged, we can use the same pattern elsewhere and close [WORKFLOWS-39](https://sagebionetworks.jira.com/browse/WORKFLOWS-39).
=> [WORKFLOWS-39] Parametrize IAM resources rather than hard-coding

config/projects/amp-ad-project.yaml
Provision Tower environment for the amp-ad project
=> add amp-ad project

config/projects/htan-project.yaml
Adds a project `yaml` file for work relating to Human Tumor atlas network
=> Add HTAN project

config/projects-dev/example-dev-project.yaml
This will enable me to start testing in `example-dev-project`
=> Bump s3 permission

config/projects/include-project.yaml
While most workflows that will be run for INCLUDE will be done on CAVATICA, I want to re-use my synindex pipeline for indexing files in Synapse.
=> Create INCLUDE Tower project

CONTRIBUTING.md, config/infra-dev/nextflow-aurora-mysql.yaml, config/infra-dev/nextflow-ecs-cluster.yaml, config/infra-dev/nextflow-ecs-security-group.yaml, config/infra-dev/nextflow-ecs-service.yaml, config/infra-dev/nextflow-ecs-task-definition.yaml, config/infra-dev/nextflow-efs-file-system.yaml, config/infra-dev/nextflow-r53-alias-record.yaml, config/infra-dev/nextflow-s3-vpc-endpoint.yaml, config/infra-dev/nextflow-tower-secret.yaml, config/infra-prod/nextflow-aurora-mysql.yaml, config/infra-prod/nextflow-ecs-cluster.yaml, config/infra-prod/nextflow-ecs-security-group.yaml, config/infra-prod/nextflow-ecs-service.yaml, config/infra-prod/nextflow-ecs-task-definition.yaml, config/infra-prod/nextflow-efs-file-system.yaml, config/infra-prod/nextflow-r53-alias-record.yaml, config/infra-prod/nextflow-s3-vpc-endpoint.yaml, config/infra-prod/nextflow-tower-secret.yaml
I forgot to update the dependency paths in the Sceptre config files, so I ran into errors during deployment. 
https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/runs/5236025506?check_suite_focus=true
=> Fix dependency paths after re-organizing configs

README.md
Updated a few links and some very minor changes to wording where I got confused. 
Also figured out how to add a Jira link that goes straight to [IT ticket creation](https://sagebionetworks.jira.com/jira/secure/CreateIssue.jspa?issuetype=3&pid=10083).
=> Minor docs changes

config/projects-prod/genie-bpc-project.yaml, config/projects-prod/genie-project.yaml
I'm creating this Tower project on behalf of the GENIE team.
=> [WORKFLOWS-93] Create Tower project for project GENIE

config/projects-prod/example-project.yaml
=> Update link to valid program codes

config/config.yaml, config/infra-dev/nextflow-ecs-task-definition.yaml, config/infra-prod/nextflow-ecs-task-definition.yaml
A patch release was just published by Seqera, so I'm updating Tower to benefit from any bug fixes.
=> Consolidate and update Tower version

config/projects-prod/genie-bpc-project.yaml
Reverts Sage-Bionetworks-Workflows/nextflow-infra#122
=> Revert "Offboard Haley from GENIE"

config/projects-prod/genie-bpc-project.yaml, templates/tower-project.yaml
Redeploys @thomasyu888's change from #122
Depends on Sage-Bionetworks/aws-infra#350
=> Offboard Haley from GENIE

config/projects-prod/nf-ntap5-biobank-jineta.yaml
I am creating this project to process additional files from the JHU-biobank. I tried launching runs from the existing ntap-add5-project but have been running into access related issues since the Synapse project has an upgraded access restriction.
Since more files are expected in this project later in the year as well as over the next few years, I think this project will be useful in running those in the future as well.
=> Create nf-ntap-biobank-jineta project

config/projects-prod/nf-ntap5-biobank-jineta.yaml
=> Fix pre-commit issues

config/projects-prod/genie-bpc-project.yaml
This is so that Chelsea can launch workflows
=> Change permissions for Chelsea

bin/configure-tower-projects.py, config/projects-prod/mc2-mcmicro-project.yaml, templates/nextflow-tower-config-bucket.yaml
=> Add external HMS collaborators to `mc2-mcmicro-project`

config/projects-prod/iatlas-project.yaml
This PR adds the iAtlas workspace to tower-prod
=> [IBCDPE-431] iAtlas workspace

bin/configure-tower-projects.py
When I merged #164, I forgot that I was waiting for a response from Seqera about the ECS configuration. This is intended as a quick follow-up PR to tweak the ECS config. Briefly, I'm extending the stop timeout to give the Nextflow head jobs enough time to terminate worker jobs, and I'm extending the start/create timeouts to give container pulls more time when network bandwidth is limited. 
However, when I was testing the change in Tower-dev, I was running into an error with my code for adding users to organizations and workspaces. Not sure how this issue didn't come up when #164 was [deployed](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/actions/runs/4301104473) last night. In any case, the code is simpler now.
=> Optimize ECS config

.github/workflows/aws-deploy.yaml
Currently no validations are run when a PR is submitted to this repo.  Update the CI to run pre-commit and jinja validation on PRs.
* Update github action plugin versions
* Enable jinja validation
* Run validations when PRs are submitted
=> [IT-2357] Test on pull requests

config/projects-dev/pec-dev-project.yaml
This creates a workspace in the dev environment for Dan Lu to test with Nextflow. No sensitive data will be worked on here.
=> Add Nextflow dev resource for dan to test
